### PR TITLE
Add Gawk

### PR DESCRIPTION
**Pull request by pmiess**
Add gnuwin32 package of gawk.

This is a broadly supported project with 173 packages in 124 repos.

This package is a dependency of the following gnuwin32 packages

- gcal.xml
- groff.xml
- netpbm.xml
- ttf2pt1.xml

This is part of 0install/0install.de-feeds#3

Moved from https://github.com/0install/repo.roscidus.com/pull/193

### CODE REVIEW

**Comment by bastianeicher** [comment]
What's the difference between `gawk.exe` and `gawk-3.1.6.exe`?

**Comment by pmiess** [comment]
I think the name is the only difference

**Comment by bastianeicher** [comment]
In that case I think it would be better to remove the `gawk-3.1.6` and `pgawk-3.1.6` `<command>`s and `<entry-point>`s. Specific version numbers in command names don't really mesh well with 0install's updating concept anyway.

**Comment by pmiess** [comment]
the 3.1.6 commands and entry points are removed

**Pull request merged**
