### PR TITLE
Add Pngcrush

### PR DESCRIPTION
**Pull request by pmiess**
Add windows package of pngcrush.

This is a supported project with 142 packages across 91 repos on repology.

 Add mingw64 pngcrush package
This depends on the mingw packages for gcc-libs #158 , zlib #159 , and png16 #160

### CODE REVIEW

**Comment by bastianeicher** [comment]
There are official Windows binaries for pngcrush available that don't depend on mingw: https://sourceforge.net/projects/pmt/files/pngcrush-executables/1.8.11/

Perhaps it would be better to use these instead in the feed?

**Comment by pmiess** [comment]
The official windows binaries are included in this feed.
They were updated January 2017
The Mingw project has released 2 updates to pngcrush,
8 updates to libpng and 3 updates zlib since then.
Do you want me to remove the mingw packages from this feed?

**Comment by bastianeicher** [comment]
Ah sorry, I overlooked the Sourceforge archives already listed in the feed.

This is a bit of a tricky judgment call I suppose. According to the pngcrush changelog the updates in 1.8.12 and 1.8.13 don't seem to be too significant, but of course it's nicer if users get the latest version of an app when using a 0install feed. On the other hand a statically linked binary with no external dependencies can be downloaded faster and is less likely to break due to too many "moving pieces".

I think I lean slightly towards removing the MinGW packages so users get the same binaries that are linked to on the [project's website](https://pmt.sourceforge.io/pngcrush/).

**Comment by pmiess** [comment]
It is done

**Pull request merged**
